a1_builders/app_core/urls.py
from django.urls import path
from app_core.views import general

app_name = 'app_core'
urlpatterns = [
    path('', general.index, name='index'),
    path('about/', general.about, name='about'),
    path('services/<int:pk>/', general.services_view, name='services_view'),
    path('works/', general.works, name='works'),
    path('faq/', general.faq, name='faq'),
    path('contact/', general.contact, name='contact'),
    path('privacy/', general.privacy, name='privacy'),
    path('mail/', general.mail_view, name='mail'),
]

a1_builders/app_user/urls.py
from django.urls import path
from app_user.views import administrator

app_name = 'app_user'

urlpatterns = [
    path(
        'login/redirect/',
        administrator.login_redirect,
        name='login-redirect'
    ),
    path(
        'administrator/index/',
        administrator.admin_index,
        name='admin_index'
    ),
    path(
        'administrator/contact_update/',
        administrator.contact_update,
        name='contact_update'
    ),
    path(
        'administrator/banner_update/',
        administrator.banner_update,
        name='banner_update'
    ),
    path(
        'administrator/about_update/',
        administrator.about_update,
        name='about_update'
    ),
    path(
        'administrator/skill_update/',
        administrator.skill_update,
        name='skill_update'
    ),
    path(
        'administrator/counter_update/',
        administrator.counter_update,
        name='counter_update'
    ),
    path(
        'administrator/services/',
        administrator.services,
        name='services'
    ),
    path(
        'administrator/service_create/',
        administrator.service_create,
        name='service_create'
    ),
    path(
        'administrator/service_update/<int:pk>/',
        administrator.service_update,
        name='service_update'
    ),
    path(
        'administrator/subservices/<int:pk>/',
        administrator.subservices,
        name='subservices'
    ),
    path(
        'administrator/subservice_create/<int:pk>/',
        administrator.subservice_create,
        name='subservice_create'
    ),
    path(
        'administrator/subservice_update/<int:pk>/',
        administrator.subservice_update,
        name='subservice_update'
    ),
    path(
        'administrator/reviews_index/',
        administrator.reviews_index,
        name='reviews_index'
    ),
    path(
        'administrator/google_business/',
        administrator.google_business,
        name='google_business'
    ),
    path(
        'administrator/google_business_create/',
        administrator.google_business_create,
        name='google_business_create'
    ),
    path(
        'administrator/google_business_update/<int:pk>/',
        administrator.google_business_update,
        name='google_business_update'
    ),
    path(
        'administrator/testimonials/',
        administrator.testimonials,
        name='testimonials'
    ),
    path(
        'administrator/testimonials_create/',
        administrator.testimonials_create,
        name='testimonials_create'
    ),
    path(
        'administrator/testimonial_update/<int:pk>/',
        administrator.testimonial_update,
        name='testimonial_update'
    ),
    path(
        'administrator/partners/',
        administrator.partners,
        name='partners'
    ),
    path(
        'administrator/partner_create/',
        administrator.partner_create,
        name='partner_create'
    ),
    path(
        'administrator/partner_update/<int:pk>/',
        administrator.partner_update,
        name='partner_update'
    ),
    path(
        'administrator/faqs/',
        administrator.faqs,
        name='faqs'
    ),
    path(
        'administrator/faq_create/',
        administrator.faq_create,
        name='faq_create'
    ),
    path(
        'administrator/faq_update/<int:pk>/',
        administrator.faq_update,
        name='faq_update'
    ),
    path(
        'administrator/privacy_update/',
        administrator.privacy_update,
        name='privacy_update'
    ),
    path(
        'administrator/works/',
        administrator.works,
        name='works'
    ),
    path(
        'administrator/work_create/',
        administrator.work_create,
        name='work_create'
    ),
    path(
        'administrator/social_media/',
        administrator.social_media,
        name='social_media'
    ),
    path(
        'administrator/social_media_create/',
        administrator.social_media_create,
        name='social_media_create'
    ),
    path(
        'administrator/social_media_update/<int:pk>/',
        administrator.social_media_update,
        name='social_media_update'
    ),
]

a1_builders/app_core/models.py
from django.db import models

# Create your models here.
import os
from django.db import models
from PIL import Image
from django.dispatch import receiver
from django.db.models.signals import pre_delete
from ckeditor.fields import RichTextField

# Opciones para el campo de selección
CATEGORY_CHOICES = [
    ('01', 'Roofing'),
    ('02', 'Flat Roofing'),
    ('04', 'Siding'),
    ('05', 'Gutter'),
    ('06', 'Window'),
    ('07', 'Carpentry'),
    ('08', 'Remodeling'),
]

SOCIAL_MEDIA_CHOICES = [
    ('01', 'Facebook'),
    ('02', 'Twitter'),
    ('03', 'Instagram'),
    ('04', 'TikTok'),
    ('05', 'YouTube'),
    ('06', 'LinkedIn'),
]

STARS_REVIEW_CHOICES = [
    ('1', '1'),
    ('2', '2'),
    ('3', '3'),
    ('4', '4'),
    ('5', '5'),
]

FLATICON_ICONS_CHOICES = [
    ('01', 'flaticon-factory'),
    ('02', 'flaticon-factory-1'),
    ('03', 'flaticon-engineer'),
    ('04', 'flaticon-valve'),
    ('05', 'flaticon-conveyor'),
    ('06', 'flaticon-oil'),
    ('07', 'flaticon-truck'),
    ('08', 'flaticon-forklift'),
    ('09', 'flaticon-voltmeter'),
    ('10', 'flaticon-fuel-truck'),
    ('11', 'flaticon-gear'),
    ('12', 'flaticon-fuel-station'),
    ('13', 'flaticon-robotic-arm'),
    ('14', 'flaticon-product'),
    ('15', 'flaticon-worker'),
    ('16', 'flaticon-robot-arm'),
    ('17', 'flaticon-help'),
    ('18', 'flaticon-conveyor-1'),
    ('19', 'flaticon-factory-2'),
    ('20', 'flaticon-optimization'),
    ('21', 'flaticon-wrench'),
    ('22', 'flaticon-crane'),
    ('23', 'flaticon-engineer-1'),
    ('24', 'flaticon-design-tools'),
    ('25', 'flaticon-construction'),
    ('26', 'flaticon-settings'),
    ('27', 'flaticon-idea'),
    ('28', 'flaticon-calculator'),
    ('29', 'flaticon-cpu'),
    ('30', 'flaticon-repair-tools'),
    ('31', 'flaticon-internet'),
    ('32', 'flaticon-analytics'),
    ('33', 'flaticon-printer'),
    ('34', 'flaticon-helmet'),
    ('35', 'flaticon-presentation'),
    ('36', 'flaticon-alarm-clock'),
    ('37', 'flaticon-bar-chart'),
    ('38', 'flaticon-microphone'),
    ('39', 'flaticon-shield'),
    ('40', 'flaticon-loupe'),
    ('41', 'flaticon-settings-1'),
    ('42', 'flaticon-monitor'),
    ('43', 'flaticon-shopping-cart'),
    ('44', 'flaticon-home'),
    ('45', 'flaticon-message'),
    ('46', 'flaticon-heart'),
    ('47', 'flaticon-user'),
    ('48', 'flaticon-play-button'),
    ('49', 'flaticon-planet-earth'),
    ('50', 'flaticon-settings-2'),
]

# Create your models here.
class AuditoriaFecha(models.Model):
    date_created = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Contact(AuditoriaFecha):
    location = models.CharField("Location", max_length=300, null=True, blank=True)
    city = models.CharField("City", max_length=100, null=True, blank=True)
    phone1 = models.CharField("Phone 2", max_length=60, null=True, blank=True)
    phone2 = models.CharField("Phone 1", max_length=60, null=True, blank=True)
    email = models.EmailField("Email", null=True, blank=True)
    latitude = models.FloatField("latitude", null=True, blank=True)
    longitude = models.FloatField("longitude", null=True, blank=True)

    def __str__(self):
        return "{0}".format(str(self.email))

    class Meta:
        ordering = ['id']
        verbose_name = 'Contact'
        verbose_name_plural = 'Contacts'


class Banner(AuditoriaFecha):
    image = models.ImageField(upload_to='banner/', null=True, blank=True)
    title = models.CharField("Banner title", max_length=300, null=True, blank=True, default="")
    title2 = models.CharField("Banner title2", max_length=300, null=True, blank=True, default="")
    subtitle = models.CharField("Banner subtitle", max_length=300, null=True, blank=True, default="")
    description = models.TextField("Description", max_length=300, null=True, blank=True)
    insurance = models.CharField("Insurance", max_length=300, null=True, blank=True, default="")

    def __str__(self):
        return "{0}".format(str(self.title))

    class Meta:
        ordering = ['id']
        verbose_name = 'Banner'
        verbose_name_plural = 'Banners'


class About(AuditoriaFecha):
    image = models.ImageField(upload_to='about/', null=True, blank=True)
    image_mission_vision = models.ImageField(upload_to='about/', null=True, blank=True)
    about = RichTextField("About", null=True, blank=True)
    mision = RichTextField("Mission", null=True, blank=True)
    vision = RichTextField("Vision", null=True, blank=True)
    image_google = models.ImageField(upload_to='about/', null=True, blank=True)
    url_google = models.URLField("URL Google Business", null=True, blank=True)

    def __str__(self):
        return "{0}".format(str(self.id))

    class Meta:
        ordering = ['id']
        verbose_name = 'About'
        verbose_name_plural = 'Abouts'


class Skill(AuditoriaFecha):
    title1 = models.CharField("Skill title 1", max_length=300, null=True, blank=True)
    description1 = models.TextField("Description 1", null=True, blank=True)
    title2 = models.CharField("Skill title 2", max_length=300, null=True, blank=True)
    description2 = models.TextField("Description 2", null=True, blank=True)
    title3 = models.CharField("Skill title 3", max_length=300, null=True, blank=True)
    description3 = models.TextField("Description 3", null=True, blank=True)

    def __str__(self):
        return "{0}".format(str(self.title1))

    class Meta:
        ordering = ['id']
        verbose_name = 'Skill'
        verbose_name_plural = 'Skills'


class Counter(AuditoriaFecha):
    title1 = models.CharField("Title 1", max_length=300, null=True, blank=True)
    number1 = models.IntegerField("Number 1", null=True, blank=True)
    symbol1 = models.CharField("Symbol 1", max_length=300, null=True, blank=True)
    title2 = models.CharField("Title 2", max_length=300, null=True, blank=True)
    number2 = models.IntegerField("Number 2", null=True, blank=True)
    symbol2 = models.CharField("Symbol 2", max_length=300, null=True, blank=True)
    title3 = models.CharField("Title 3", max_length=300, null=True, blank=True)
    number3 = models.IntegerField("Number 3", null=True, blank=True)
    symbol3 = models.CharField("Symbol 3", max_length=300, null=True, blank=True)
    title4 = models.CharField("Title 4", max_length=300, null=True, blank=True)
    number4 = models.IntegerField("Number 4", null=True, blank=True)
    symbol4 = models.CharField("Symbol 4", max_length=300, null=True, blank=True)

    def __str__(self):
        return "{0}".format(str(self.title1))

    class Meta:
        ordering = ['id']
        verbose_name = 'Counter'
        verbose_name_plural = 'Counters'


class Service(AuditoriaFecha):
    image = models.ImageField(upload_to='service/', null=True, blank=True)
    image_large = models.ImageField(upload_to='service/', null=True, blank=True)
    icon = models.CharField("Icon", max_length=2, choices=FLATICON_ICONS_CHOICES, null=True, blank=True)
    title = models.CharField("Service Name", max_length=300, null=True, blank=True)
    description = RichTextField("Description", null=True, blank=True)
    description_finish = RichTextField("Finish Description", null=True, blank=True)

    def __str__(self):
        return "{0}".format(str(self.title))

    class Meta:
        ordering = ['id']
        verbose_name = 'Service'
        verbose_name_plural = 'Services'


class SubService(AuditoriaFecha):
    service = models.ForeignKey(Service, on_delete=models.CASCADE, related_name='service_subservice')
    image = models.ImageField(upload_to='subservice/', null=True, blank=True)
    title = models.CharField("Subservice Name", max_length=300, null=True, blank=True)
    description = RichTextField("Description", null=True, blank=True)

    def __str__(self):
        return "{0}".format(str(self.title))

    class Meta:
        ordering = ['id']
        verbose_name = 'SubService'
        verbose_name_plural = 'SubServices'


class WorkImage(AuditoriaFecha):
    category = models.CharField("Category", null=True, blank=True, max_length=2, choices=CATEGORY_CHOICES)
    title = models.CharField("Image title", max_length=300, null=True, blank=True)
    description = models.TextField("Description", null=True, blank=True)
    image = models.ImageField(upload_to='work_image/')

    def __str__(self):
        return "{0}".format(str(self.title))

    def bytes_to_mb(self, bytes):
        mb = bytes / 1000000
        return mb

    def save(self, *args, **kwargs):
        if not self._state.adding:
            super().save(*args, **kwargs)
            return
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)
        # Obtiene el tamaño de la imagen en bytes
        image_size = os.path.getsize(self.image.path)
        img_size_mb = self.bytes_to_mb(image_size)

        if img_size_mb < 1:
            img_quality = 50
        elif img_size_mb > 3:
            img_quality = 18
        else:
            img_quality = 30

        # Obtiene el ancho y alto de la imagen
        width, height = img.size
        if width > 1920 or height > 1920:
            # Definir el nuevo ancho máximo
            max_size = 1920
            # Redimensionar la imagen con el ancho máximo proporcionado
            img.thumbnail((max_size, max_size))

        img.save(self.image.path, quality=img_quality)

    class Meta:
        ordering = ['id']
        verbose_name = 'WorkImage'
        verbose_name_plural = 'WorkImages'


@receiver(pre_delete, sender=WorkImage)
def delete_gallery_image(sender, instance, **kwargs):
    file_path = instance.image.path
    if os.path.exists(file_path):
        os.remove(file_path)


class Testimonial(AuditoriaFecha):
    image = models.ImageField(upload_to='testimonial/', null=True, blank=True)
    name = models.CharField("Name", max_length=300, null=True, blank=True)
    location = models.CharField("Location", max_length=300, null=True, blank=True)

a1_builders/app_user/models.py
from django.db import models

# Create your models here.

a1_builders/templates/app_user/snippets/footer.html
<!-- footer content -->
<footer>
  <div class="pull-right">
    &copy; <script>document.write(new Date().getFullYear())</script> A1 Builders All rights reserved
  </div>
  <div class="clearfix"></div>
</footer>
<!-- /footer content -->

a1_builders/templates/app_user/snippets/google_business.html
{% load static %}

<div class="">
    <div class="page-title">
        <div class="title_left" style="padding-bottom: 12px;">
            <h3> Google Business Reviews <small></small> </h3>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>List <small></small></h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <a href="{% url 'app_user:google_business_create' %}" type="button" class="btn btn-info" style="color: white;">Add Google Business Review</a>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <table id="faqTable">
                        <thead>
                            <tr>
                                <th style="width: 40%;">Name</th>
                                <th style="width: 40%;">Description</th>
                                <th style="width: 20%;">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for review in testimonials %}
                            <tr>
                                <td>{{review.name}}</td>
                                <td>{{review.description|truncatechars_html:45|safe}}</td>
                                <td>
                                    <a class="btn btn-success" href="{% url 'app_user:google_business_update' review.id %}">Update</a>
                                    <button class="btn btn-danger" data-toggle="modal" data-target="#deleteReview{{ forloop.counter }}">Delete</button>
                                </td>
                            </tr>
                            <!-- start FAQ's delete modal -->
                                {% include 'app_user/snippets/google_business_delete_modal.html' %}
                            <!-- end FAQ's -->
                        {% endfor %}
                        </tbody>
                        <tfoot>
                            <tr>
                                <th>Title</th>
                                <th>Description</th>
                                <th>Action</th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

a1_builders/templates/app_user/snippets/google_business_delete_modal.html
<!-- Modal -->
<div class="modal fade" id="deleteReview{{ forloop.counter }}" tabindex="-1" role="dialog"
    aria-labelledby="deleteReviewCenter" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Delete Google Business Review</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="post">
                    {% csrf_token %}
                    <p style="font-size: 18px;">Are you sure you want to delete this Google Business Review? This action
                        cannot be undone, and all
                        information associated with this testimonial will be permanently removed.</p>
                    <input type="hidden" value="{{ review.id }}" name="id_to_delete">
                    <hr>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" name="delete_testimonial" class="btn btn-danger">Delete</button>

                </form>
            </div>

        </div>
    </div>
</div>

a1_builders/templates/app_user/snippets/menu.html
{% load static %}

<div class="col-md-3 left_col">
    <div class="left_col scroll-view">
      <div class="navbar nav_title" style="border: 0;">
        <a href="{% url 'account_login' %}" class="site_title">
          <!-- <i class="fa fa-paw"></i> -->
          <i style="border: 0;"><img src="{% static 'app_user/images/header_admin.webp' %}" alt="logo_menu"></i>
          <span>A1 Builders</span>
        </a>
      </div>

      <div class="clearfix"></div>

      <!-- menu profile quick info -->
      <div class="profile clearfix">
        <div class="profile_pic">
          <img src="{% static 'app_user/images/user.png' %}" alt="..." class="img-circle profile_img">
        </div>
        <div class="profile_info">
          {% if user.is_authenticated %}
            <span>Welcome,</span>
            <h2>{{ user.username }}</h2>
          {% endif %}
        </div>
      </div>
      <!-- /menu profile quick info -->

      <br />

      <!-- sidebar menu -->
      <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
        <div class="menu_section">
          <h3>Dashboard</h3>
          <ul class="nav side-menu">
            <li>
              <a href="{% url 'app_user:admin_index' %}"><i class="fa fa-home"></i> Home </a>
            </li>
          </ul>
          <hr>
          <h3>General</h3>
          <ul class="nav side-menu">
            <li>
              <a href="{% url 'app_user:about_update' %}"><i class="fa fa-institution"></i> About </a>
            </li>
            <li>
              <a href="{% url 'app_user:banner_update' %}"><i class="fa fa-laptop"></i> Banner </a>
            </li>
            <li>
              <a href="{% url 'app_user:contact_update' %}"><i class="fa fa-user"></i> Contact </a>
            </li>
            <li>
              <a href="{% url 'app_user:counter_update' %}"><i class="fa fa-area-chart"></i> Counter </a>
            </li>
            <li>
              <a href="{% url 'app_user:faqs' %}"><i class="fa fa-check-square-o"></i> FAQ's </a>
            </li>
            <li>
              <a href="{% url 'app_user:partners' %}"><i class="fa fa-bolt"></i> Partner </a>
            </li>
            <li>
              <a href="{% url 'app_user:privacy_update' %}"><i class="fa fa-file"></i> Privacy </a>
            </li>
            <li>
              <a href="{% url 'app_user:services' %}"><i class="fa fa-sitemap"></i> Services </a>
            </li>
            <li>
              <a href="{% url 'app_user:social_media' %}"><i class="fa fa-facebook"></i> Social Media </a>
            </li>
            <li>
              <a href="{% url 'app_user:reviews_index' %}"><i class="fa fa-comment"></i> Testimonial </a>
            </li>
            <li>
              <a href="{% url 'app_user:skill_update' %}"><i class="fa fa-cogs"></i> Why Us </a>
            </li>
            <li>
              <a href="{% url 'app_user:works' %}"><i class="fa fa-image"></i> Works </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>

a1_builders/templates/app_user/snippets/partners.html
{% load static %}

<div class="">
    <div class="page-title">
        <div class="title_left" style="padding-bottom: 12px;">
            <h3> Partners <small></small> </h3>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>List <small></small></h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <a href="{% url 'app_user:partner_create' %}" type="button" class="btn btn-info" style="color: white;">Add Partner</a>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <table id="partnerTable">
                        <thead>
                            <tr>
                                <th style="width: 70%;">Image</th>
                                <th style="width: 30%;">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for partner in partners %}
                            <tr>
                                <td>
                                {% if partner.image  %}
                                    <img style="width: 12%; display: block;" src="{{ partner.image.url }}" alt="image" />
                                {% else %}
                                    <img style="width: 12%; display: block;" src="{% static 'app_core/construction/images/logo-1.png' %}" alt="image">
                                {% endif %}
                                </td>
                                <td>
                                    <a class="btn btn-success" href="{% url 'app_user:partner_update' partner.id %}">Update</a>
                                    <button class="btn btn-danger" data-toggle="modal" data-target="#deletePartner{{ forloop.counter }}">Delete</button>
                                </td>
                            </tr>
                            <!-- start FAQ's delete modal -->
                                {% include 'app_user/snippets/partner_delete_modal.html' %}
                            <!-- end FAQ's -->
                        {% endfor %}
                        </tbody>
                        <tfoot>
                            <tr>
                                <th style="width: 70%;">Image</th>
                                <th style="width: 30%;">Action</th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

a1_builders/templates/app_user/snippets/reviews_index.html
<div class="">
    <div class="page-title">
        <div class="title_left">
            <h3>Reviews - Testimonials</h3>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="top_tiles">

                <div class="col-lg-3 col-md-3 col-sm-12  ">
                    <a href="{% url 'app_user:google_business' %}">
                        <div class="x_panel fixed_height_200">
                            <div class="x_content">
                                <div class="flex">
                                    <ul class="list-inline widget_profile_box">
                                        <li>
                                        </li>
                                        <li >
                                            <div class="icon" style="text-align: center;"><i class="fa fa-google icono-grande"></i></div>
                                        </li>
                                        <li>
                                        </li>
                                    </ul>
                                </div>
                                <h3 class="name" style="text-align: center; padding-top: 18px;">Google Business Review</h3>
                            </div>
                        </div>
                    </a>
                </div>

                <div class="col-lg-3 col-md-3 col-sm-12  ">
                    <a href="{% url 'app_user:testimonials' %}">
                        <div class="x_panel fixed_height_200">
                            <div class="x_content">
                                <div class="flex">
                                    <ul class="list-inline widget_profile_box">
                                        <li>
                                        </li>
                                        <li >
                                            <div class="icon" style="text-align: center;"><i class="fa fa-comment icono-grande"></i></div>
                                        </li>
                                        <li>
                                        </li>
                                    </ul>
                                </div>
                                <h3 class="name" style="text-align: center; padding-top: 18px;">Testimonials</h3>
                            </div>
                        </div>
                    </a>
                </div>

            </div>
        </div>
    </div>
</div>

a1_builders/templates/app_user/snippets/social_media.html
{% load static %}

<div class="">
    <div class="page-title">
        <div class="title_left" style="padding-bottom: 12px;">
            <h3> Social Media <small></small> </h3>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>List <small></small></h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <a href="{% url 'app_user:social_media_create' %}" type="button" class="btn btn-info" style="color: white;">Add Social Media</a>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <table id="socialMediaTable">
                        <thead>
                            <tr>
                                <th style="width: 40%;">Name</th>
                                <th style="width: 40%;">Url</th>
                                <th style="width: 20%;">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for social in social_media %}
                            <tr>
                                <td>{{social.get_name_display}}</td>
                                <td><a href="{{social.url}}" target="_blank">{{social.url}}</a></td>
                                <td>
                                    <a class="btn btn-success" href="{% url 'app_user:social_media_update' social.id %}">Update</a>
                                    <button class="btn btn-danger" data-toggle="modal" data-target="#deleteSocialMedia{{ forloop.counter }}">Delete</button>
                                </td>
                            </tr>
                            <!-- start FAQ's delete modal -->
                                {% include 'app_user/snippets/social_media_delete_modal.html' %}
                            <!-- end FAQ's -->
                        {% endfor %}
                        </tbody>
                        <tfoot>
                            <tr>
                                <th>Name</th>
                                <th>Url</th>
                                <th>Action</th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

a1_builders/templates/app_user/snippets/subservice_delete_modal.html
<!-- Modal -->
<div class="modal fade" id="deleteSubservice{{ forloop.counter }}" tabindex="-1" role="dialog" aria-labelledby="deleteSubserviceCenter" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">Delete Subservice</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            <form method="post">
                {% csrf_token %}
                <p style="font-size: 18px;">Are you sure you want to delete this Subservice? This action cannot be undone, and all information associated with this testimonial will be permanently removed.</p>
                <input type="hidden" value="{{ subservice.id }}" name="deleteSubserviceInput">
                <hr>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit"  name="delete_testimonial" class="btn btn-danger">Delete</button>
                
            </form>
        </div>
        
      </div>
    </div>
  </div>