a1_builders/app_core/urls.py
from django.urls import path
from app_core.views import general

app_name = 'app_core'
urlpatterns = [
    path('', general.index, name='index'),
    path('about/', general.about, name='about'),
    path('services/<int:pk>/', general.services_view, name='services_view'),
    path('works/', general.works, name='works'),
    path('faq/', general.faq, name='faq'),
    path('contact/', general.contact, name='contact'),
    path('privacy/', general.privacy, name='privacy'),
    path('mail/', general.mail_view, name='mail'),
]

a1_builders/app_user/urls.py
from django.urls import path
from app_user.views import administrator

app_name = 'app_user'

urlpatterns = [
    path(
        'login/redirect/',
        administrator.login_redirect,
        name='login-redirect'
    ),
    path(
        'administrator/index/',
        administrator.admin_index,
        name='admin_index'
    ),
    path(
        'administrator/contact_update/',
        administrator.contact_update,
        name='contact_update'
    ),
    path(
        'administrator/banner_update/',
        administrator.banner_update,
        name='banner_update'
    ),
    path(
        'administrator/about_update/',
        administrator.about_update,
        name='about_update'
    ),
    path(
        'administrator/skill_update/',
        administrator.skill_update,
        name='skill_update'
    ),
    path(
        'administrator/counter_update/',
        administrator.counter_update,
        name='counter_update'
    ),
    path(
        'administrator/services/',
        administrator.services,
        name='services'
    ),
    path(
        'administrator/service_create/',
        administrator.service_create,
        name='service_create'
    ),
    path(
        'administrator/service_update/<int:pk>/',
        administrator.service_update,
        name='service_update'
    ),
    path(
        'administrator/subservices/<int:pk>/',
        administrator.subservices,
        name='subservices'
    ),
    path(
        'administrator/subservice_create/<int:pk>/',
        administrator.subservice_create,
        name='subservice_create'
    ),
    path(
        'administrator/subservice_update/<int:pk>/',
        administrator.subservice_update,
        name='subservice_update'
    ),
    path(
        'administrator/reviews_index/',
        administrator.reviews_index,
        name='reviews_index'
    ),
    path(
        'administrator/google_business/',
        administrator.google_business,
        name='google_business'
    ),
    path(
        'administrator/google_business_create/',
        administrator.google_business_create,
        name='google_business_create'
    ),
    path(
        'administrator/google_business_update/<int:pk>/',
        administrator.google_business_update,
        name='google_business_update'
    ),
    path(
        'administrator/testimonials/',
        administrator.testimonials,
        name='testimonials'
    ),
    path(
        'administrator/testimonials_create/',
        administrator.testimonials_create,
        name='testimonials_create'
    ),
    path(
        'administrator/testimonial_update/<int:pk>/',
        administrator.testimonial_update,
        name='testimonial_update'
    ),
    path(
        'administrator/partners/',
        administrator.partners,
        name='partners'
    ),
    path(
        'administrator/partner_create/',
        administrator.partner_create,
        name='partner_create'
    ),
    path(
        'administrator/partner_update/<int:pk>/',
        administrator.partner_update,
        name='partner_update'
    ),
    path(
        'administrator/faqs/',
        administrator.faqs,
        name='faqs'
    ),
    path(
        'administrator/faq_create/',
        administrator.faq_create,
        name='faq_create'
    ),
    path(
        'administrator/faq_update/<int:pk>/',
        administrator.faq_update,
        name='faq_update'
    ),
    path(
        'administrator/privacy_update/',
        administrator.privacy_update,
        name='privacy_update'
    ),
    path(
        'administrator/works/',
        administrator.works,
        name='works'
    ),
    path(
        'administrator/work_create/',
        administrator.work_create,
        name='work_create'
    ),
    path(
        'administrator/social_media/',
        administrator.social_media,
        name='social_media'
    ),
    path(
        'administrator/social_media_create/',
        administrator.social_media_create,
        name='social_media_create'
    ),
    path(
        'administrator/social_media_update/<int:pk>/',
        administrator.social_media_update,
        name='social_media_update'
    ),
]

a1_builders/app_core/views/general.py
import logging
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.shortcuts import render
from app_core.models import Contact, Banner, About, Skill, Counter, Service, SubService, WorkImage, Testimonial, \
    Partner, Faq, Privacy, SocialMedia

# Get an instance of a logger
logger = logging.getLogger(__name__)


def index(request):
    contact = Contact.objects.all().last()
    banner = Banner.objects.all().last()
    about = About.objects.all().last()
    skills = Skill.objects.all().last()
    indicators = Counter.objects.all().last()
    servicios = Service.objects.all()
    works = WorkImage.objects.all().order_by('?')[:6]
    testimonials = Testimonial.objects.all().order_by('?')
    partners = Partner.objects.all()
    social_media = SocialMedia.objects.all()
    context = {
        'contact': contact,
        'banner': banner,
        'about': about,
        'skills': skills,
        'indicators': indicators,
        'servicios': servicios,
        'works': works,
        'testimonials': testimonials,
        'partners': partners,
        'social_media': social_media
    }

    if request.method == 'POST':
        if 'stay_connected' in request.POST:
            email = request.POST.get('userEmail')
            send_msg_stay_connected(email)
            return render(request, 'app_core/pages/index.html', context)
    else:
        # Renderizar el template con ambos formularios
        return render(request, 'app_core/pages/index.html', context)


def about(request):
    contact = Contact.objects.all().last()
    about = About.objects.all().last()
    skills = Skill.objects.all().last()
    servicios = Service.objects.all()
    indicators = Counter.objects.all().last()
    testimonials = Testimonial.objects.all().order_by('?')
    social_media = SocialMedia.objects.all()
    works = WorkImage.objects.all().order_by('?')[:1]
    partners = Partner.objects.all()
    context = {
        'contact': contact,
        'servicios': servicios,
        'about': about,
        'indicators': indicators,
        'skills': skills,
        'testimonials': testimonials,
        'works': works,
        'social_media': social_media,
        'partners': partners
    }
    if request.method == 'POST':
        if 'stay_connected' in request.POST:
            email = request.POST.get('userEmail')
            send_msg_stay_connected(email)
            return render(request, 'app_core/pages/about.html', context)
    else:
        # Renderizar el template con ambos formularios
        return render(request, 'app_core/pages/about.html', context)


def services(request):
    contact = Contact.objects.all().last()
    servicios = Service.objects.all()
    social_media = SocialMedia.objects.all()
    works = WorkImage.objects.all().order_by('?')[:1]
    context = {
        'contact': contact,
        'servicios': servicios,
        'works': works,
        'social_media': social_media
    }
    if request.method == 'POST':
        if 'stay_connected' in request.POST:
            email = request.POST.get('userEmail')
            send_msg_stay_connected(email)
            return render(request, 'app_core/pages/services.html', context)
    else:
        # Renderizar el template con ambos formularios
        return render(request, 'app_core/pages/services.html', context)


def services_view(request, pk):
    contact = Contact.objects.all().last()
    servicios = Service.objects.all()
    servicio = Service.objects.get(pk=pk)
    subservicios = SubService.objects.filter(service=pk)
    works = WorkImage.objects.all().order_by('?')[:1]
    social_media = SocialMedia.objects.all()
    testimonials = Testimonial.objects.all().order_by('?')
    context = {
        'contact': contact,
        'servicio': servicio,
        'servicios': servicios,
        'subservicios': subservicios,
        'works': works,
        'social_media': social_media,
        'testimonials': testimonials
    }
    if request.method == 'POST':
        if 'stay_connected' in request.POST:
            email = request.POST.get('userEmail')
            send_msg_stay_connected(email)
            return render(request, 'app_core/pages/service.html', context)
    else:
        # Renderizar el template con ambos formularios
        return render(request, 'app_core/pages/service.html', context)


def works(request):
    contact = Contact.objects.all().last()
    servicios = Service.objects.all()
    gallery = WorkImage.objects.all().order_by('?')
    social_media = SocialMedia.objects.all()
    about = About.objects.all().last()
    context = {
        'contact': contact,
        'servicios': servicios,
        'works': gallery,
        'about': about,
        'social_media': social_media
    }
    if request.method == 'POST':
        if 'stay_connected' in request.POST:
            email = request.POST.get('userEmail')
            send_msg_stay_connected(email)
            return render(request, 'app_core/pages/works.html', context)
    else:
        # Renderizar el template con ambos formularios
        return render(request, 'app_core/pages/works.html', context)


def faq(request):
    contact = Contact.objects.all().last()
    faqs = Faq.objects.all()
    servicios = Service.objects.all()
    works = WorkImage.objects.all().order_by('?')[:1]
    social_media = SocialMedia.objects.all()
    context = {
        'contact': contact,
        'servicios': servicios,
        'faqs': faqs,
        'social_media': social_media,
        'works': works
    }
    if request.method == 'POST':
        if 'stay_connected' in request.POST:
            email = request.POST.get('userEmail')
            send_msg_stay_connected(email)
            return render(request, 'app_core/pages/faq.html', context)
    else:
        # Renderizar el template con ambos formularios
        return render(request, 'app_core/pages/faq.html', context)


def contact(request):
    contact = Contact.objects.all().last()
    servicios = Service.objects.all()
    testimonials = Testimonial.objects.all().order_by('?')
    social_media = SocialMedia.objects.all()
    works = WorkImage.objects.all().order_by('?')[:1]
    about = About.objects.all().last()
    context = {
        'servicios': servicios,
        'contact': contact,
        'about': about,
        'testimonials': testimonials,
        'social_media': social_media,
        'works': works
    }
    if request.method == 'POST':
        if 'stay_connected' in request.POST:
            email = request.POST.get('userEmail')
            send_msg_stay_connected(email)
            return render(request, 'app_core/pages/contact.html', context)

        elif 'contact_us_form' in request.POST:
            username = request.POST.get('userName')
            email = request.POST.get('userEmail')
            phone = request.POST.get('userPhone')
            message = request.POST.get('userMessage')
            send_msg_contact_us(username, email, phone, message)
            return render(request, 'app_core/pages/contact.html', context)
        else:
            return render(request, 'app_core/pages/contact.html', context)
    else:
        # Renderizar el template con ambos formularios
        return render(request, 'app_core/pages/contact.html', context)


def privacy(request):
    contact = Contact.objects.all().last()
    servicios = Service.objects.all()
    privacy = Privacy.objects.all().last()
    social_media = SocialMedia.objects.all()
    works = WorkImage.objects.all().order_by('?')[:1]
    testimonials = Testimonial.objects.all().order_by('?')
    partners = Partner.objects.all()
    context = {
        'contact': contact,
        'servicios': servicios,
        'privacy': privacy,
        'social_media': social_media,
        'works': works,
        'testimonials': testimonials,
        'partners': partners
    }
    if request.method == 'POST':
        if 'stay_connected' in request.POST:
            email = request.POST.get('userEmail')
            send_msg_stay_connected(email)
            return render(request, 'app_core/pages/privacy.html', context)
    else:
        # Renderizar el template con ambos formularios
        return render(request, 'app_core/pages/privacy.html', context)


def send_msg_stay_connected(email):
    subject = 'You got a subscribe message from A1 Builders website'
    message = f'Hello A1 Builders! someone has contact you and wants to be a new subscriber: \n\nEmail: {email}.'
    from_email = 'Roofing Messenger <roofing.messenger.service@gmail.com>'
    recipient_list = ['camilobentrenandolatinos@gmail.com']
    send_mail(subject, message, from_email, recipient_list)


def send_msg_contact_us(username, email, phone, get_message):
    subject = 'You got a contact message from A1 Builders website'
    message = f'Hello A1 Builders! you got a contact message from website: \n\nUsername: {username} \nEmail: {email} \nPhone: {phone} \n\nMessage: {get_message}'
    from_email = 'Roofing Messenger <roofing.messenger.service@gmail.com>'
    recipient_list = ['camilobentrenandolatinos@gmail.com']
    send_mail(subject, message, from_email, recipient_list)


def mail_view(request):
    return HttpResponseRedirect(
        'https://accounts.zoho.com/signin?servicename=VirtualOffice&signupurl=https://www.zoho.com/workplace/pricing.html/')

a1_builders/templates/app_core/snippets/about.html
{% load static %}

<!-- Content Section -->
<div class="section-full content-inner const-about">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 col-md-6 col-sm-12 col-12 wow fadeInLeft" data-wow-duration="2s" data-wow-delay="0.3s">
                <div class="radius-sm m-b30 img-ho1">
                    <img src="{% static 'app_core/images/about/pic11.jpg' %}" alt=""/>
                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-12 wow fadeInRight" data-wow-duration="2s" data-wow-delay="0.6s">
                <div class="content-bx1">
                    <div class="about-year">
                        <span>26</span>
                        <p>Years<br/>Experience<br/>Working</p>
                    </div>
                    <div class="section-head style2">
                        <h2 class="title">Architecure is a visual art,<br/> and The Building</h2>
                        <p>Praesent pharetra orci odio, ut mattis tellus ullamcorper ornare. Suspendisse ullamcorper metus in erat viverra, vehicula pharetra dolor accumsan. In arcu ex, rutrum finibus malesuada vel. Praesent pharetra orci odio, ut mattis tellus</p>
                    </div>
                    <a href="portfolio-details.html" class="site-button m-r10 m-b10 btnhover20">View Portfolio</a>
                    <a href="about-1.html" class="site-button black m-b10 btnhover20">About Us</a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Content Section End -->

a1_builders/templates/app_core/snippets/banner_privacy.html
{% load static %}

<!-- inner page banner -->
<div class="dlab-bnr-inr overlay-black-middle bg-pt" style="background-image:url('{% static 'app_core/images/banner/bnr9.webp' %}');">
    <div class="container">
        <div class="dlab-bnr-inr-entry">
            <h1 class="text-white">Our Privacy Policy</h1>
            <!-- Breadcrumb row -->
            <div class="breadcrumb-row">
                <ul class="list-inline">
                    <li><a href="{% url 'app_core:index' %}">Home</a></li>
                    <li>Privacy</li>
                </ul>
            </div>
            <!-- Breadcrumb row END -->
        </div>
    </div>
</div>
<!-- inner page banner END -->

a1_builders/templates/app_core/snippets/faq_section2.html
{% load static %}

<div class="section-full bg-white content-inner">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="sort-title clearfix text-center">
                    <h3>General Questions</h3>
                </div>
                <div class="dlab-accordion box-sort-in m-b30 primary space active-bg" id="accordion005">

                    {% for faq in faqs %}
                        <div class="panel">
                            <div class="acod-head">
                                <h6 class="acod-title">
                                    <a href="javascript:void(0);" data-toggle="collapse" aria-expanded="true"
                                       data-target="#collapse{{ forloop.counter }}">
                                        {{ faq.title }}
                                    </a>
                                </h6>
                            </div>

                            <div id="collapse{{ forloop.counter }}" class="acod-body collapse"
                                 data-parent="#accordion005">
                                <div class="acod-content">
                                    {{ faq.description|safe }}
                                </div>
                            </div>
                        </div>
                    {% endfor %}

                </div>
            </div>
        </div>
        <!-- Accordion Bg Primary END -->
    </div>
</div>

a1_builders/templates/app_core/snippets/footer.html
{% load static %}

<!-- Footer -->
<footer class="site-footer footer-gray-1 style1">
    <!-- newsletter part -->
    <div class="dlab-newsletter">
        <div class="container">
            <div class="ft-contact wow fadeIn" data-wow-duration="2s" data-wow-delay="0.6s">
                <div class="ft-contact-bx">
                    <img src="{% static 'app_core/images/icon/icon1.png' %}" alt=""/>
                    <h4 class="title">Address</h4>
                    <p>{{ contact.location }}, <br> {{ contact.city }}</p>
                </div>
                <div class="ft-contact-bx">
                    <img src="{% static 'app_core/images/icon/icon2.png' %}" alt=""/>
                    <h4 class="title">Phone</h4>
                    <p id="contactPhone"></p>
                </div>
                <div class="ft-contact-bx">
                    <img src="{% static 'app_core/images/icon/icon3.png' %}" alt=""/>
                    <h4 class="title">Email Contact</h4>
                    <p>{{ contact.email }}</p>
                </div>
            </div>
        </div>
    </div>
    <!-- footer top part -->
    <div class="footer-top">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 col-sm-12 wow fadeIn" data-wow-delay="0.2s">
                    <div class="widget border-0">
                        <h6 class="m-b20 text-white font-weight-300 text-uppercase">Quick Links</h6>
                        <ul class="list-2">
                            <li><a href="{% url 'app_core:about' %}">About Us</a></li>
                            <li><a href="{% url 'app_user:works' %}">Works</a></li>
                            <li><a href="{% url 'app_core:faq' %}">Faqs</a></li>
                            <li><a href="{% url 'app_core:contact' %}">Contact</a></li>
                            <li><a href="{% url 'app_core:privacy' %}">Privacy</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-12 wow fadeIn" data-wow-delay="0.4s">
                    <div class="widget">
                        <h6 class="m-b20 text-white font-weight-300 text-uppercase">Subscribe</h6>
                        <div class="subscribe-form m-b20 m-t30">
                            <form method="post">
                                {% csrf_token %}
                                <div class="input-group">
                                    <input name="userEmail" class="form-control radius-no" placeholder="Your Email"
                                           type="email" required>
                                    <span class="input-group-btn">
                                        <button name="stay_connected" type="submit"
                                                class="site-button btnhover20 radius-no">SEND</button>
                                    </span>
                                </div>
                            </form>
                        </div>
                        <h6 class="m-b10 text-white font-weight-300 text-uppercase">Connect with us</h6>
                        <ul class="list-inline m-a0">
                            <li><a href="javascript:void(0);" class="site-button btnhover20 facebook sharp"><i
                                    class="fa fa-facebook"></i></a></li>
                            <li><a href="javascript:void(0);" class="site-button btnhover20 google-plus sharp"><i
                                    class="fa fa-google-plus"></i></a></li>
                            <li><a href="javascript:void(0);" class="site-button btnhover20 linkedin sharp"><i
                                    class="fa fa-linkedin"></i></a></li>
                            <li><a href="javascript:void(0);" class="site-button btnhover20 instagram sharp"><i
                                    class="fa fa-instagram"></i></a></li>
                            <li><a href="javascript:void(0);" class="site-button btnhover20 twitter sharp"><i
                                    class="fa fa-twitter"></i></a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-5 col-md-12 col-sm-12 wow fadeIn" data-wow-delay="0.6s">
                    <div class="icon-bx-wraper bx-style-1 m-b15 p-a30 radius-sm br-col-w1 bg-tpw1">
                        <h5 class="text-white font-weight-300">{{ about.about|safe|truncatewords:31 }}</h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- footer bottom part -->
    <div class="footer-bottom">
        <div class="container">
            <div class="row" style="padding: 10px 0;">
                <div class="col-md-6 col-sm-6 text-left "><span>Copyright © <span id="yearValue"></span><a
                        href="javascript:;">A1 Builders</a> all rights reserved.</span></div>
                <div class="col-md-6 col-sm-6 text-right ">
                    <div class="widget-link ">
                        <ul>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- Footer END -->

a1_builders/templates/app_core/snippets/gallery.html
{% load static %}

<div class="bg-white lightgallery gallery-filters" id="lightgallery">
    <div class="section-full content-inner-2">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 section-head text-center">
                    <div class=" clearfix">
                        <h2 class="title">Our Works</h2>
                    </div>
                    <div class="dlab-separator-outer ">
                        <div class="dlab-separator bg-primary style-icon text-white radius-xl"><i
                                class="fa fa-leaf"></i></div>
                    </div>
                </div>
                <div class="col-lg-12 text-center">
                    <!-- <div class="site-filters style1 clearfix m-b20">
                        <ul class="filters1" data-toggle="buttons">
                            <li data-filter="" class="btn active"><input type="radio"><a href="javascript:void(0);"><span>All</span></a></li>
                            <li data-filter="nature" class="btn"><input type="radio"><a href="javascript:void(0);"><span>Nature</span></a></li>
                            <li data-filter="fashion" class="btn"><input type="radio"><a href="javascript:void(0);"><span>Fashion</span></a></li>
                            <li data-filter="woman" class="btn"><input type="radio"><a href="javascript:void(0);"><span>Woman</span></a></li>
                            <li data-filter="man" class="btn"><input type="radio"><a href="javascript:void(0);"><span>Man</span></a></li>
                            <li data-filter="animal" class="btn"><input type="radio"><a href="javascript:void(0);"><span>Animal</span></a></li>
                            <li data-filter="pet" class="btn"><input type="radio"><a href="javascript:void(0);"><span>Pet</span></a></li>
                        </ul>
                    </div> -->
                </div>
            </div>
            <div class="clearfix">
                <ul id="masonry1" class="dlab-gallery-listing gallery text-center sp10">

                    {% for work in works %}
                        <li class="card-container m-b10 col-lg-6 nature">
                            <div class="dlab-media dlab-img-overlay1 dlab-img-effect">
                                <img src="{{ work.image.url }}" alt="" width="800"
                                     height="650"/>
                                <div class="overlay-bx">
                                    <div class="overlay-icon"> 
                                    <span data-exthumbimage="{{ work.image.url }}"
                                          data-src="{{ work.image.url }}"
                                          class="check-km" title="{{ work.title }}">		
                                        <i class="ti-zoom-in icon-bx-xs"></i> 
                                    </span>
                                    </div>
                                </div>
                            </div>
                        </li>
                    {% endfor %}


                </ul>
            </div>
        </div>
    </div>
</div>

a1_builders/templates/app_core/snippets/insurance.html
{% load static %}

a1_builders/templates/app_core/snippets/mission_vision.html
{% load static %}

a1_builders/templates/app_core/snippets/privacy_section.html
{% load static %}

<div class="content-block">
    <!-- Privacy Policy -->
    <div class="section-full content-inner inner-text">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h4 class="title">The Industrial Privacy Policy was updated on 25 June 2018.</h4>
                    <p class="font-18">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages,<a href="javascript:void(0);"> Contact Us </a>and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
                    <div class="dlab-divider bg-gray-dark"></div>
                    <h4 class="title">Who We Are and What This Policy Covers</h4>
                    <p class="font-18">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
                    <div class="dlab-divider bg-gray-dark"></div>
                    <h4 class="title">What personal information we collect</h4>
                    <ul class="list-circle primary m-a0">
                        <li>The Industrial Privacy Policy was updated on 25 June 2018. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's </li>
                        <li>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</li>
                        <li>Remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</li>
                        <li>Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</li>
                        <li>Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- Privacy Policy END -->
</div>

a1_builders/templates/app_core/snippets/services3.html
{% load static %}

<!-- Content -->
<div class="page-content bg-white">
    <!-- contact area -->
    <div class="content-area">
        <div class="container max-w900">

            {% for service in servicios %}

                <!-- Blog large img -->
                <div class="blog-post blog-lg blog-rounded">
                    <div class="dlab-post-media dlab-img-effect zoom-slow">
                        <a href="{% url 'app_core:services_view' service.pk %}">
                            <img src="{{ service.image_large.url }}" alt="{{ service.title }}">
                        </a>
                    </div>
                    <div class="dlab-info p-a25 border-1">
                        <div class="dlab-post-meta">
                        </div>
                        <div class="dlab-post-title">
                            <h4 class="post-title"><a
                                    href="{% url 'app_core:services_view' service.pk %}">{{ service.title }}</a></h4>
                        </div>
                        <div class="dlab-post-text">
                            <p>{{ service.description|safe }}</p>
                        </div>
                        <div class="dlab-post-readmore">
                            <a href="{% url 'app_core:services_view' service.pk %}" title="READ MORE" rel="bookmark"
                               class="site-button">READ MORE
                                <i class="ti-arrow-right"></i>
                            </a>
                        </div>
                    </div>
                </div>
                <!-- Blog large img END -->

            {% endfor %}

        </div>
    </div>
</div>
<!-- Content END-->